# Generated by Django 5.1.4 on 2025-01-10 04:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phongtros.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('SDT', models.SmallIntegerField(null=True)),
                ('vaiTro', models.IntegerField(choices=[(1, 'QUANTRIVIEN'), (2, 'CHUNHATRO'), (3, 'NGUOITHUETRO')], default=phongtros.models.VaiTro['QUANTRIVIEN'])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BaiDang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(upload_to='nguoidungs/%Y/%m')),
                ('tuongTac', models.ManyToManyField(to='phongtros.nguoidung')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('phongtros.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('tenTro', models.CharField(max_length=255)),
                ('anhTro', models.ImageField(upload_to='phongtros/%Y/%m/')),
                ('diaChi', models.CharField(max_length=255)),
                ('gia', models.PositiveIntegerField()),
                ('soNguoiO', models.SmallIntegerField()),
                ('nguoiChoThue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtros.nguoidung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('thongTin', models.CharField(max_length=255)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('baiDang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtros.baidang')),
                ('nguoiBinhLuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtros.nguoidung')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='baidang',
            name='nguoiDangBai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtros.nguoidung'),
        ),
        migrations.CreateModel(
            name='BaiDangChoThue',
            fields=[
                ('baidang_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='phongtros.baidang')),
                ('troChoThue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtros.tro')),
            ],
            options={
                'abstract': False,
            },
            bases=('phongtros.baidang',),
        ),
    ]
