# Generated by Django 5.1.4 on 2025-01-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tro',
            name='anhTro',
        ),
        migrations.CreateModel(
            name='AnhTro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anh', models.ImageField(upload_to='phongtros/%Y/%m/')),
                ('tro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtros.tro')),
            ],
        ),
    ]
