# Generated by Django 5.1.4 on 2025-01-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anhtro',
            name='tro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anh_tros', to='phongtros.tro'),
        ),
    ]
