# Generated by Django 5.1.4 on 2025-01-12 15:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phongtros', '0002_alter_anhtro_tro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baidang',
            name='thongTin',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
