# Generated by Django 5.1.4 on 2025-01-14 14:22

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtros', '0003_alter_baidang_thongtin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tuongTac',
            field=models.ManyToManyField(related_name='tuong_tac', to=settings.AUTH_USER_MODEL),
        ),
    ]
