"""
Django settings for phongtroapi project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

import oauth2_provider.contrib.rest_framework
from ckeditor_demo.settings import CKEDITOR_UPLOAD_PATH

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4wl=pt6+#21lpjfl3abf0)x2vtih+^yuc^kz=w$c!gvj3x_t+l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['toquocbinh2102.pythonanywhere.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'phongtros.apps.PhongtrosConfig',
    'rest_framework',
    'vi_address',
    'drf_yasg',
    'ckeditor',
    'ckeditor_uploader',
    'oauth2_provider',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # 'oauth2_provider.middleware.OAuth2TokenMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'phongtroapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'phongtroapi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'toquocbinh2102$phongtrodb',
        'USER': 'toquocbinh2102',
        'PASSWORD': 'admin@123',
        'HOST': 'toquocbinh2102.mysql.pythonanywhere-services.com'  # mặc định localhost
    }
}

import pymysql

pymysql.install_as_MySQLdb()

AUTH_USER_MODEL = 'phongtros.User'

MEDIA_URL = '/media/'
MEDIA_ROOT = '%s/phongtros/static/' % BASE_DIR

CKEDITOR_UPLOAD_PATH = 'baidangs/'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

import os



STATIC_ROOT = os.path.join(BASE_DIR, "static")

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK ={
    'DEFAULT_AUTHENTICATION_CLASSES':
        (
            'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        )
}

import cloudinary

cloudinary.config(
    cloud_name="dbhhpljbo",
    api_key="769838993333676",
    api_secret="sKhPxCraBaikLWgXkceg2nwZox8",
    secure=True
)

# OAUTH2_PROVIDER = {
#     'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore',
    # 'SCOPES': {
    #     'read': 'Read access',
    #     'write': 'Write access',
    # },
    # 'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,  # Token hết hạn sau 1 giờ
    # 'ALLOW_CLIENT_SECRET_POST': True,    # Cho phép gửi `client_secret` qua POST
# }

# CLIENT_ID = 'xM7SzMPKueVwgeyJwTTZXuvKWG70jjrDXjvhkK5v'
# CLIENT_SECRET = '123456'